### ISSUE TITLE
insert_cnl, delete_cnl methods output

### ISSUE THREAD

**Issue by jswiatkowski** [cognitum-octopus/cognipy#12]
![image](https://user-images.githubusercontent.com/70372816/104610344-4fd59000-5684-11eb-8576-b32d3a666e95.png)

Names of methods suggests that you can insert/delete any CNL yet if you insert/delete incorrect cnl like subsumption in attached pic error occures. Maybe output can be prettier?

**Comment by kcieslinski** [comment]
Done
