### ISSUE TITLE
ValueError: To many values to unpack

### ISSUE THREAD

**Issue by kuba3538** [cognitum-octopus/cognipy#13]
Both owls produces same issue:
https://sites.google.com/site/ontoworks/ontologies/DSA_04092015.owl?attredirects=0&d=1
https://www.isibang.ac.in/~bisu/ontology/instOntology.owl

![image](https://user-images.githubusercontent.com/41238327/108967522-ef247480-767f-11eb-94c0-9493ab4b8189.png)

**Comment by kaplan196883** [comment]
should be fixed
