### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by kuba3538** [cognitum-octopus/cognipy#14]
https://www.isibang.ac.in/~bisu/ontology/mod-ontology-09092016.owl
1. load ontology with Ontology constructor
2. use draw_graph() method
3.  
![image](https://user-images.githubusercontent.com/41238327/108968272-db2d4280-7680-11eb-97a9-13dabeb16129.png)

**Comment by kaplan196883** [comment]
should be fixed
