### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by jswiatkowski** [cognitum-octopus/cognipy#21]
when loading http://krr-nas.cs.ox.ac.uk/ontologies/lib/BioPAX/biopax-level2/biopax-example-ecocyc-glycolysis/v1.0/00007.owl
![image](https://user-images.githubusercontent.com/70372816/111028319-258b1f00-83f6-11eb-8155-5cccbc675dab.png)

**Comment by kaplan196883** [comment]
Cannot reproduce in the newest version
