### ISSUE TITLE
RiotException

### ISSUE THREAD

**Issue by jswiatkowski** [cognitum-octopus/cognipy#22]
when loading http://krr-nas.cs.ox.ac.uk/ontologies/lib/BAMS/neuron-ontology/2009-10-28/00006.owl

![image](https://user-images.githubusercontent.com/70372816/111028370-8581c580-83f6-11eb-8849-5dca6beb0625.png)

**Comment by kcieslinski** [comment]
Not a bug - ontology not compliant with W3C standard.
